services:
  # main 서비스 (Nginx)
  service-docker-main:
    image: soyoung0/nginx:1.29.7-docker-main
    # build:
    #   context: ./main
    #   dockerfile: Dockerfile
    #   platforms: ["linux/amd64", "linux/arm64"]
    container_name: docker-main-nginx-container
    restart: always
    ports:
      - "8080:80"
    networks:
      - board-network

  # docker-install (Nginx)
  service-docker-install:
    image: soyoung0/nginx:1.29.7-docker-install
    build:
      context: ./docker-install
      dockerfile: Dockerfile
      platforms: ["linux/amd64", "linux/arm64"]
    container_name: docker-install-nginx-container
    restart: always
    ports:
      - "8081:80"
    networks:
      - board-network

networks:
  board-network:
    driver: bridge
